package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage configuration",
	Long: `Manage go-jf-org configuration.

The config command provides subcommands for initializing and managing
the tool's configuration file.`,
}

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Create default configuration file",
	Long: `Initialize creates a default configuration file at ~/.go-jf-org/config.yaml.

This command will:
  - Create the ~/.go-jf-org directory if it doesn't exist
  - Generate a config.yaml file with sensible defaults
  - Create cache and transaction log directories

If a configuration file already exists, it will not be overwritten
unless the --force flag is used.`,
	RunE: runConfigInit,
}

var configInitForce bool

func init() {
	rootCmd.AddCommand(configCmd)
	configCmd.AddCommand(configInitCmd)
	
	configInitCmd.Flags().BoolVarP(&configInitForce, "force", "f", false, "overwrite existing configuration file")
}

func runConfigInit(cmd *cobra.Command, args []string) error {
	// Get home directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	// Define paths
	configDir := filepath.Join(homeDir, ".go-jf-org")
	configFile := filepath.Join(configDir, "config.yaml")
	cacheDir := filepath.Join(configDir, "cache")
	txnDir := filepath.Join(configDir, "txn")

	// Check if config file already exists
	if _, err := os.Stat(configFile); err == nil && !configInitForce {
		return fmt.Errorf("configuration file already exists at %s\nUse --force to overwrite", configFile)
	}

	// Create config directory
	log.Info().Str("dir", configDir).Msg("Creating configuration directory")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Create cache directory
	log.Debug().Str("dir", cacheDir).Msg("Creating cache directory")
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return fmt.Errorf("failed to create cache directory: %w", err)
	}

	// Create transaction log directory
	log.Debug().Str("dir", txnDir).Msg("Creating transaction log directory")
	if err := os.MkdirAll(txnDir, 0755); err != nil {
		return fmt.Errorf("failed to create transaction directory: %w", err)
	}

	// Default configuration content
	configContent := `# go-jf-org Configuration File
# Automatically generated by 'go-jf-org config init'

# Source directories to scan for media files
sources:
  - /media/unsorted

# Destination directories for organized media
destinations:
  movies: /media/jellyfin/movies
  tv: /media/jellyfin/tv
  music: /media/jellyfin/music
  books: /media/jellyfin/books

# API keys for metadata enrichment (optional - uses free tier if not provided)
api_keys:
  tmdb: ""  # Get from https://www.themoviedb.org/settings/api

# Organization options
organize:
  create_nfo: true           # Generate Jellyfin-compatible NFO files
  download_artwork: true     # Download posters, fanart, and album covers
  normalize_names: true      # Normalize file and directory names

# Safety options
safety:
  dry_run: false                    # Preview mode - don't actually move files
  transaction_log: true             # Log all operations for rollback support
  conflict_resolution: skip         # How to handle conflicts: skip | rename | interactive
`

	// Write configuration file
	log.Info().Str("file", configFile).Msg("Writing configuration file")
	if err := os.WriteFile(configFile, []byte(configContent), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	// Success message
	fmt.Println()
	fmt.Printf("✓ Configuration initialized successfully!\n\n")
	fmt.Printf("Configuration file created at:\n  %s\n\n", configFile)
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit the configuration file to match your setup")
	fmt.Println("  2. Update source and destination paths")
	fmt.Println("  3. Optionally add TMDB API key for enhanced metadata")
	fmt.Println()
	fmt.Printf("Try scanning a directory:\n")
	fmt.Printf("  go-jf-org scan /path/to/media\n")
	fmt.Println()

	return nil
}
